import React, { useState } from 'react';
import { fetchUrlContent, generateLearningPlan } from '../lib/ai';
import type { AIGeneratedPlan } from '../lib/ai';
import { getApiKey, saveApiKey } from '../lib/storage';
import { useHero } from '../context/HeroContext';
import { Sparkles, X, Link, Key, Check } from 'lucide-react';

interface AIGeneratorModalProps {
  onClose: () => void;
}

export const AIGeneratorModal: React.FC<AIGeneratorModalProps> = ({ onClose }) => {
  const { addFullTopic } = useHero();
  
  const [apiKey, setApiKeyValue] = useState(getApiKey());
  const [url, setUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedPlan, setGeneratedPlan] = useState<AIGeneratedPlan | null>(null);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!apiKey.trim()) {
      setError('Bitte gib einen Gemini API Key ein.');
      return;
    }
    if (!url.trim()) {
      setError('Bitte gib eine gültige URL ein.');
      return;
    }

    saveApiKey(apiKey);
    setIsLoading(true);
    setError(null);

    try {
      const textConfig = await fetchUrlContent(url);
      const plan = await generateLearningPlan(apiKey, textConfig);
      setGeneratedPlan(plan);
    } catch (err: any) {
        if(err?.message && err.message.includes("API key not valid")){
            setError('Der eingegebene API Key ist ungültig.');
        } else {
            setError(err.message || 'Ein unerwarteter Fehler ist aufgetreten.');
        }
    } finally {
      setIsLoading(false);
    }
  };

  const handleConfirm = () => {
    if (!generatedPlan) return;
    
    addFullTopic({
      title: generatedPlan.topicTitle,
      description: generatedPlan.topicDescription,
      quests: generatedPlan.quests.map(q => ({
        id: '', // Will be generated by addFullTopic
        title: q.title,
        description: q.description || '',
        xpValue: q.xpValue,
        completed: false,
        createdAt: 0
      }))
    });

    onClose();
  };

  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(4px)',
      display: 'flex', justifyContent: 'center', alignItems: 'center',
      zIndex: 50, padding: '1rem'
    }}>
      <div className="glass-panel" style={{ width: '100%', maxWidth: '600px', maxHeight: '90vh', overflowY: 'auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
          <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-color)' }}>
            <Sparkles /> AI Quest Generator
          </h2>
          <button onClick={onClose} style={{ color: 'var(--text-muted)' }}><X /></button>
        </div>

        {!generatedPlan ? (
          <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{ background: 'rgba(0,0,0,0.2)', padding: '1rem', borderRadius: '8px' }}>
              <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                <Key size={16} /> Google Gemini API Key
              </label>
              <input 
                type="password"
                className="input-field" 
                placeholder="AIzaSy..." 
                value={apiKey}
                onChange={(e) => setApiKeyValue(e.target.value)}
              />
              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>
                Bleibt lokal gespeichert. Wird für die Analyse des Inhalts benötigt.
              </p>
            </div>

            <div>
               <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                <Link size={16} /> Link zur Webseite (Artikel, Tutorial, etc.)
              </label>
              <input 
                type="url"
                className="input-field" 
                placeholder="https://..." 
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                required
              />
            </div>

            {error && <div style={{ color: '#ef4444', padding: '0.5rem', background: 'rgba(239, 68, 68, 0.1)', borderRadius: '4px' }}>{error}</div>}

            <button type="submit" className="btn-primary" disabled={isLoading} style={{ justifyContent: 'center', marginTop: '1rem' }}>
              {isLoading ? 'Analysiere und Generiere...' : <><Sparkles size={18} /> Plan generieren</>}
            </button>
          </form>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <div style={{ textAlign: 'center' }}>
              <h3 style={{ color: 'var(--primary-color)', fontSize: '1.5rem', marginBottom: '0.5rem' }}>{generatedPlan.topicTitle}</h3>
              <p style={{ color: 'var(--text-muted)' }}>{generatedPlan.topicDescription}</p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <h4 style={{ color: 'var(--text-main)', borderBottom: '1px solid var(--surface-border)', paddingBottom: '0.5rem' }}>
                Generierte Quests ({generatedPlan.quests.length})
              </h4>
              {generatedPlan.quests.map((quest, i) => (
                <div key={i} style={{ background: 'rgba(0,0,0,0.2)', padding: '0.75rem', borderRadius: '8px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <div style={{ fontWeight: '500' }}>{quest.title}</div>
                    {quest.description && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{quest.description}</div>}
                  </div>
                  <div style={{ color: 'var(--primary-color)', fontWeight: 'bold', whiteSpace: 'nowrap' }}>+{quest.xpValue} XP</div>
                </div>
              ))}
            </div>

            <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
              <button onClick={() => setGeneratedPlan(null)} className="btn-secondary" style={{ flex: 1 }}>
                Zurück
              </button>
              <button id="btn-confirm-plan" onClick={handleConfirm} className="btn-primary" style={{ flex: 2, justifyContent: 'center' }}>
                <Check size={18} /> Plan übernehmen
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
